

spring:
  profiles:
    active: @spring.profiles.active@
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    prefix: classpath:/templates/
    suffix: .html  #后缀名
    mode: HTML
    cache: false
    encoding: UTF-8
    #     新版本不支持content-type: text/html，故新写法
    servlet:
      content-type: text/html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

